### ISSUE TITLE
Error saat menjalankan composer install pertama kali

### ISSUE THREAD

**Issue by Azzammi** [sandinur157/tuturial-membuat-aplikasi-point-of-sales#1]
![image](https://user-images.githubusercontent.com/23116326/121870262-12f1f000-cd2d-11eb-9f79-2690b27d67f3.png)
Kenapa ya mas?

**Comment by sandinur157** [comment]
Arrow function mulai di perkenalkan di PHP semenjak versi 7.4, nah itu errornya karena mgkin versi PHP yg digunakan di bawah 7.4, coba upgrade versi php bisa download xampp yg udh bundling, cek aja requirements sesuai yg ada di README.md

**Comment by Azzammi** [comment]
oiya maaf versi php yang digunakan tidak sesuai ternyata, oke terima kasih
